name: dbt_Snowflake_Capstone
version: "1.0.0"
config-version: 2

profile: capstone

model-paths:
  - models

macro-paths:
  - macros

snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

models:
  dbt_Snowflake_Capstone:
    bronze:
      +database: CT_VARNAN_DEWANGAN_DB
      +schema: CAPSTONE
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: append_new_columns
      +tags:
        - bronze

    silver:
      +database: CT_VARNAN_DEWANGAN_DB
      +schema: SILVER
      +materialized: view
      +tags:
        - silver
